export default [
  { value: 'c', icons: ['fa-c'], width: 1, keyDetect: 'del', event: 'clear' },
  { value: 'ac', icons: ['fa-a', 'fa-c'], width: 1, keyDetect: 'none', event: 'clearAll' },
  { value: 'backspace', icons: ['fa-arrow-left-long'], width: 1, keyDetect: 'backspace', event: 'delete' },
  { value: 'history', icons: ['fa-clock-rotate-left'], width: 1, keyDetect: 'none', event: 'history' },
  { value: '/', icons: ['fa-divide'], width: 1, keyDetect: '/', event: 'divide' },
  { value: '7', icons: ['fa-7'], width: 1, keyDetect: '7', event: 'setNumber' },
  { value: '8', icons: ['fa-8'], width: 1, keyDetect: '8', event: 'setNumber' },
  { value: '9', icons: ['fa-9'], width: 1, keyDetect: '9', event: 'setNumber' },
  { value: 'squareRoot', icons: ['fa-square-root-variable'], width: 1, keyDetect: 'none', event: 'squareRoot' },
  { value: '*', icons: ['fa-xmark'], width: 1, keyDetect: '*', event: 'multiply' },
  { value: '4', icons: ['fa-4'], width: 1, keyDetect: '4', event: 'setNumber' },
  { value: '5', icons: ['fa-5'], width: 1, keyDetect: '5', event: 'setNumber' },
  { value: '6', icons: ['fa-6'], width: 1, keyDetect: '6', event: 'setNumber' },
  { value: 'power', icons: ['fa-xmark'], extraText: 'ʸ', width: 1, keyDetect: 'none', event: 'power' },
  { value: '-', icons: ['fa-minus'], width: 1, keyDetect: '-', event: 'subtract' },
  { value: '1', icons: ['fa-1'], width: 1, keyDetect: '1', event: 'setNumber' },
  { value: '2', icons: ['fa-2'], width: 1, keyDetect: '2', event: 'setNumber' },
  { value: '3', icons: ['fa-3'], width: 1, keyDetect: '3', event: 'setNumber' },
  { value: '%', icons: ['fa-percent'], width: 1, keyDetect: '%', event: 'percentage' },
  { value: '+', icons: ['fa-plus'], width: 1, keyDetect: '+', event: 'add' },
  { value: '0', icons: ['fa-0'], width: 1, keyDetect: '0', event: 'setNumber' },
  { value: '00', icons: ['fa-0', 'fa-0'], width: 1, keyDetect: 'none', event: 'setNumber' },
  { value: ',', extraText: ',', width: 1, keyDetect: ',', event: 'setComma' },
  { value: '=', icons: ['fa-equals'], width: 2, keyDetect: '=', event: 'getResult' },
]